name: Docker Image CI

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Enter to target sub dir
      run: cd mcp/apisix-mcp
    - name: Build Apisix Image
      run: docker build --tag shaw/apisix:$(date +%s) .
